Bloodlines refactor reducer
jonnykry/expresso pull request #10
Opened 2017-02-24 05:45 UTC by ghmeier

@jonnykry and I talked earlier about consolidating the reducers and
actions to make less boilerplate for the bloodlines (and dashboard)
code. This is the first attempt to remove unnecessary duplication in
the actions and reducers.

It turns out that all of the functionality of the previous code can
be easily replicated with just three action types rather than three
for each as previous. This means that we reduce code replication
by a significant amount, and consolidate our error handling to just
one or two components rather than scattering it throughout the state.

This also adds a TIMEOUT action to clear the modify state after a
specified number of milliseconds. This is useful for 'refreshing'
state between routes as well as fading error/success messages.

After this refactor, I'm under the suspicion that we could consolidate
many of our actions under these few action types and the 'modify'
reducer. The only code we'd have to write would be the action code
which makes sense since urls and parameter interpretation are similar
from request to request.

2017-02-24 06:42 UTC, ghmeier commented on src/actions/bloodlinesActions.js
> +export const TIMEOUT = "TIMEOUT";
consolidated from 20+ to 8 constants...

2017-02-24 06:48 UTC, ghmeier reviewed
Highlighted the interesting code. Most of the other stuff is just the aftermath of refactoring the action names, etc..

2017-02-24 06:48 UTC, ghmeier commented on src/actions/bloodlinesActions.js
> +function handlePagedRequest(item, url, type, offset, limit) {
rather than duplicate the paging get requests throughout actions, this helper function runs them and calls the correct action type.

2017-02-24 06:48 UTC, ghmeier commented on src/actions/bloodlinesActions.js
> +function handleRequest(url, type, body) {
This handles any request other than a paged one. making everything else just url construction which was the only difference in the functions before.

2017-02-24 06:48 UTC, ghmeier commented on src/actions/userActions.js
> +            if (!json.success) {
This change got in but isn't related to the PR, but our json responses can also error, and the `.catch` block doesn't catch it. However, `json.success` will be true if there's no error.

2017-02-24 06:48 UTC, ghmeier commented on src/reducers/bloodlinesReducer.js
> +	if (action.itemType !== TRIGGERS) {
This is the thing i'm most uncertain about, but i wanted to consolidate the below function while still returning separate states for the different objects so we can access all triggers and all contents in their respective containers.

2017-02-24 06:48 UTC, ghmeier commented on src/reducers/bloodlinesReducer.js
> +export function modify(state = {
One glorious fucking function for the previous 6. Holla.

2017-02-25 18:49 UTC, jonnykry requested changes
This is a really awesome PR, but I think we should make the `actionTypes.js` (and maybe the utility function) changes for sure...  whether or not we do that here is entirely up to you!  I'm cool to merge and do a follow-up.

Let me know which you want to do!

2017-02-25 18:49 UTC, jonnykry commented on src/actions/bloodlinesActions.js
> +export const TIMEOUT = "TIMEOUT";
I've looked around and it seems we could do something like this:

(NEW) `actionTypes.js`
```
export default {
  FETCH_ME: 'FETCH_ME',
  FETCH_LIKES: 'FETCH_LIKES',
  FETCH_TRACKS: 'FETCH_TRACKS',
  FETCH_USER: 'FETCH USER'
};
```

`bloodlinesActions.js`
```
import ActionTypes from './actionTypes';
...
ActionTypes.ERROR
...
```

`bloodlinesReducer.js`
```
import ActionTypes from './actionTypes';
...
ActionTypes.ERROR
...
```

Would you be interested in adding this here?  We can do it in a follow-up if you want too!  I think it reduces boiler plate on the Reducer end for imports and consolidates all the constants for consistent action naming.

2017-02-25 18:49 UTC, jonnykry commented on src/actions/bloodlinesActions.js
> +function handleRequest(url, type, body) {
I wonder, can we can put these functions into a `actionUtilities.js` and use them across all actions?

2017-02-25 18:49 UTC, jonnykry commented on src/reducers/bloodlinesReducer.js
> +export function modify(state = {
hahaha you just killed like 400 lines of code this is awesome.

2017-02-25 19:05 UTC, merged