Roaster orders
jonnykry/expresso pull request #103
Opened 2017-04-20 19:33 UTC by lcollin

2017-04-20 20:27 UTC, ghmeier requested changes

2017-04-20 20:27 UTC, ghmeier commented on src/components/dashboard/orders/OrderContainer.js
> +        if (this.state.send) {
we don't need all of these. orders aren't created by the roaster, and the only thing they should update id getting the tracking url.

2017-04-20 20:27 UTC, ghmeier commented on src/components/dashboard/orders/OrderContainer.js
> +    handleEditBeans(e) {
don't need this

2017-04-20 20:27 UTC, ghmeier commented on src/components/dashboard/orders/OrderContainer.js
> +    getAddType(key) {
don't need this.

2017-04-20 20:27 UTC, ghmeier commented on src/components/dashboard/orders/OrderContainer.js
> +    handleEditPhoto(file) {
don't need this.

2017-04-20 20:27 UTC, ghmeier commented on src/components/dashboard/orders/OrderContainer.js
> +    getNumber(s) {
use this for validating packaging info.

2017-04-20 20:27 UTC, ghmeier commented on src/components/dashboard/orders/OrderEdit.js
> +class OrderEdit extends Component {
I don't think we need this component at all. We should have a 'PackagingInfoContainer' and 'PackagingInfo' component instead.

2017-04-20 20:27 UTC, ghmeier commented on src/components/dashboard/orders/Order.js
> +            key: 'id',
we don't need `orderId` this value doesn't make sense to users. We need the name of the item that the order references, the amount, and the date the order was created

2017-04-20 20:38 UTC, jonnykry approved these changes

2017-04-20 20:38 UTC, jonnykry commented on src/components/dashboard/inventory/InventoryContainer.js
> +        console.log("successful inventories 2");
remove clg

2017-04-20 20:38 UTC, jonnykry commented on src/components/dashboard/orders/OrderContainer.js
> +        console.log(this.props);
remove clg

2017-04-25 17:36 UTC, ghmeier approved these changes

2017-04-25 19:23 UTC, merged