Bean card
jonnykry/expresso pull request #80
Opened 2017-04-11 21:16 UTC by jakelong95

Handles #66

2017-04-11 22:23 UTC, ghmeier requested changes
I think there could be some more effort put into considering what users need to see rather than just listing the raw text from the user.

2017-04-11 22:23 UTC, ghmeier commented on src/components/dashboard/browse/BeanItemDetails.js
>                      <div>Item ID: {this.props.bean.id}</div>
users dont need to see an id

2017-04-11 22:23 UTC, ghmeier commented on src/components/dashboard/browse/BeanItemDetails.js
>                      <div>Location: {this.props.roaster.addressLine1} - {(this.props.roaster.addressLine2 + ' ' || '') + this.props.roaster.addressState}
this is not relevant to bean details

2017-04-11 22:23 UTC, ghmeier commented on src/components/dashboard/browse/BeanItemDetails.js
> +                    }
we can also add bean.tags which is an array of strings representing tags.

2017-04-12 04:51 UTC, jonnykry commented
Should display the quantity (e.g., "1 lb"), too

2017-04-12 23:28 UTC, ghmeier approved these changes
Looks good. Nice to have the input validation.

Might want to look at jazzing up the styling a bit.

2017-04-12 23:29 UTC, merged