Change item and roaster reducers to index by id
jonnykry/expresso pull request #92
Opened 2017-04-18 04:13 UTC by ghmeier

This makes some breaking changes to how we use `roaster`, `roasterItem`, and `beans` stores, so I'm requesting a review from everyone. I'll comment on the important areas so you can avoid the miscellaneous style changes.

Prior to this PR we had two separate but related problems.
1. Roaster,  Roaster Item and Bean actions were creating race conditions between components. For example, you could go to the bean details page, and then try to look at the roaster account and you'd see the beans owned by the roaster of the previous item. There were a couple other instances of this (the more by this roaster page), and more were cropping up as we kept using these stores in more and more places. 
2. There are a growing number of places where we want to reference data by id, but we want to avoid making a large number of api calls each time we load the page. One example of this is the user subscriptions page where it makes sense to display the subscribed items right with each subscription but it would require either composing objects on the back end, or making all the api calls on the front end and trying to get them stored correctly. 

So, my solution is to instead index these items by id in the stores and have requests add key/value pairs to the stores when they complete rather than completely overwriting the data. This way, getting multiple roasters just stores the roaster info rather than overwriting it which will prevent us from making the call in the future. It's most apparent for items where we store the results of `getAllItems` in the same `beans` store as items retrieved from individual subscriptions and we just get them by id, only sending a request if we need to.

So this pr fixes the issues with roaster info not updating and removes the race conditions we had before. Examples of usage will be commented.

Also, subscriptions look nice. 

![subs](https://cloud.githubusercontent.com/assets/5702686/25114303/684b05ae-23c3-11e7-875b-9ed56a0eb154.png)

2017-04-18 04:23 UTC, ghmeier commented on src/components/dashboard/browse/BeanItemDetailsContainer.js
> +        return this.props.bean[this.props.params.id];
Now, we get the bean from a set of objects with itemId as their key.

2017-04-18 04:23 UTC, ghmeier commented on src/components/dashboard/browse/BeanItemDetailsContainer.js
> +        return this.props.roasters[this.bean().roasterId];
same goes for roaster. it's actually a set of roaster object that we can retrieve by id.

2017-04-18 04:23 UTC, ghmeier commented on src/components/dashboard/browse/BeanItemDetailsContainer.js
> +        bean: state.beans.items,
we can access the stores like so.

2017-04-18 04:23 UTC, ghmeier commented on src/components/dashboard/roaster/Roaster.js
> +            child = React.cloneElement(this.props.children, {roaster: this.roaster()});
we can pass the correct roaster down through props now :+1:

2017-04-18 04:23 UTC, ghmeier commented on src/components/dashboard/subscriptions/SubscribeContainer.js
> +    bean() {
this method is just shorthand for getting the bean based on id

2017-04-18 04:23 UTC, ghmeier commented on src/components/dashboard/subscriptions/SubscriptionContainer.js
> +        if (this.props.beans[this.props.item.itemId]) {
getting a bean from itemIds in subscriptions.

2017-04-18 04:23 UTC, ghmeier commented on src/reducers/configureReducers.js
> -    bean,
the individual bean store was a problem, so it's gone now.

2017-04-18 04:23 UTC, ghmeier commented on src/reducers/reducerUtil.js
> +                ..._contents,
this *copies*  the existing contents and then sets the result to an additional key based on the payload data. 

from my experience this won't create duplicates.

2017-04-18 04:38 UTC, jakelong95 approved these changes
LGTM, this is a really good idea imo

2017-04-18 21:15 UTC, jonnykry requested changes
Sorry for so many comments this round, nothing too crazy though :octocat:

2017-04-18 21:15 UTC, jonnykry commented on src/components/dashboard/browse/BeanItem.js
> +        const tagClass = 'br1 bg-gold pa2 ma1 dib';
maybe a #nit but can `dib` be `flex`?  I think we should preference `flex` in most cases unless `display` is necessary.

2017-04-18 21:15 UTC, jonnykry commented on src/components/dashboard/browse/BeanItemDetailsContainer.js
> +        return this.props.bean[this.props.params.id];
the singular `bean` is not actually singular in this case, right?  we should use `beans` for consistency imo, even if our intention is to only grab a singular bean

2017-04-18 21:15 UTC, jonnykry commented on src/components/dashboard/subscriptions/SubscribeContainer.js
> +        bean: state.beans.items,
duplicate of previous comment here too

2017-04-18 21:15 UTC, jonnykry commented on src/components/dashboard/subscriptions/Subscription.js
> +        }
huge nit-pick to stir up controversy.  there's a ternary and incredible variable name opportunity:

```
const bagTag = bean && item.quantity > 1 ? 'bags' : 'bag'; 
```

2017-04-18 21:15 UTC, jonnykry commented on src/components/dashboard/subscriptions/SubscriptionContainer.js
> +        if (this.props.beans[this.props.item.itemId]) {
using `beans` here, no update needed

2017-04-18 21:15 UTC, jonnykry commented on src/components/dashboard/subscriptions/SubscriptionListContainer.js
> +import React, {Component, PropTypes} from 'react';
I noticed we weren't breaking lists into containers, good to refactor/use containers for them - nice!

2017-04-18 21:15 UTC, jonnykry commented on src/reducers/reducerUtil.js
> +                ..._contents,
im a bit confused by this, why are the array brackets necessary on the following line?  we're just mapping keys to objects here right?  is that what prevents duplicates?

2017-04-18 21:28 UTC, yuderekyu approved these changes
Forgot to actually submit the review - this is a dope pr.

2017-04-19 01:33 UTC, ghmeier commented on src/reducers/reducerUtil.js
> +                ..._contents,
I honestly don't know for certain, i saw it that way in examples and assumed is was the common syntax... it's been in reducer util the whole time for all the paged reducers.

2017-04-19 02:02 UTC, merged